obj-y					+= alpine_machine.o
obj-y					+= al_fabric.o
obj-y 					+= al_hal/
obj-$(CONFIG_SMP)			+= platsmp.o alpine_cpu_pm.o
obj-$(CONFIG_PCI)			+= pcie_of.o
obj-$(CONFIG_PCI_MSI)			+= msix.o
obj-$(CONFIG_ARM_CPU_IDLE_ALPINE)	+= sleep-alpine.o
