obj-$(CONFIG_PINCTRL_FAKE)                              += pinctrl-fake.o

pinctrl-fake-$(CONFIG_PINCTRL_FAKE)                     += pinctrl-fake-main.o

pinctrl-fake-$(CONFIG_PINCTRL_FAKE_GPIO)                += pinctrl-fake-gpio.o
pinctrl-fake-$(CONFIG_PINCTRL_FAKE_GPIO_WORKER)         += pinctrl-fake-gpio-worker.o

pinctrl-fake-$(CONFIG_PINCTRL_FAKE_I2C)                 += pinctrl-fake-i2c.o
pinctrl-fake-$(CONFIG_PINCTRL_FAKE_I2C_AT24)            += pinctrl-fake-i2c-at24.o
pinctrl-fake-$(CONFIG_PINCTRL_FAKE_I2C_MCP9808)         += pinctrl-fake-i2c-mcp9808.o
pinctrl-fake-$(CONFIG_PINCTRL_FAKE_I2C_MCP9808_WORKER)  += pinctrl-fake-i2c-mcp9808-worker.o

#pinctrl-fake-$(CONFIG_PINCTRL_FAKE_SPI)  += pinctrl-fake-spi.o
#pinctrl-fake-$(CONFIG_PINCTRL_FAKE_MMC)  += pinctrl-fake-mmc.o
#pinctrl-fake-$(CONFIG_PINCTRL_FAKE_UART) += pinctrl-fake-uart.o
#pinctrl-fake-$(CONFIG_PINCTRL_FAKE_PWM)  += pinctrl-fake-uart.o
